apiVersion: v1
kind: Secret
metadata:
  name: har-backend-secrets
  namespace: har-local
type: Opaque
stringData:
  # Mapbox (both geocoding and directions/isochrones use the same token)
  GEOCODING_API_KEY: "pk.eyJ1IjoidGF6cmlhbiIsImEiOiJjbWdvOTcwMHgwaGR1MmxwdmppZWJwZ3h1In0.aXeKSKpOtyLlroFjZcbjZw"
  ROUTING_API_KEY:   "pk.eyJ1IjoidGF6cmlhbiIsImEiOiJjbWdvOTcwMHgwaGR1MmxwdmppZWJwZ3h1In0.aXeKSKpOtyLlroFjZcbjZw"

  # Mapillary
  MAPILLARY_TOKEN:   "MLY|25104743642490002|86e6631f5a6ffdcc6e5c2852e096d28e"

  # Optional: if added a different POI key later
  POI_API_KEY: ""
