apiVersion: v1
kind: Service
metadata:
  name: har-redis
  namespace: har-local
  labels:
    app: har-redis
spec:
  type: ClusterIP
  selector:
    app: har-redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
